changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - dependabot
  categories:
    - title: ✨ New Features
      labels:
        - enhancement
        - feature
    - title: 🐛 Bug Fixes
      labels:
        - bug
        - fix
    - title: 🧪 Tests
      labels:
        - test
        - tests
    - title: 📝 Documentation
      labels:
        - documentation
        - docs
    - title: 🔧 Maintenance
      labels:
        - chore
        - maintenance
        - refactor
    - title: Other Changes
      labels:
        - '*'
